unique_ids:
  forms:
    AccountHistory: GRPZKW6GFCMPUPNOOQ35KICUENEFREJ4
    AccountHistoryRowTemplate: DTQC4QNV22UIY5G3XRBZHNPHSSW2EAFY
    BalanceSheet: JVV5Y6Z5R7W4FG44WZBE4VOFDJ5QBUYL
    BalanceSheetRowTemplate: I4UNNGMEKL3DC6IJDTY3WBADGGOOFIKQ
    Home: 7S2PNXIMR7BVTLZUF2DHIQS3Q3VHQ2MO
    NewTransaction: 6UIIFTBGIVXSYKBKFFZG3NLLQGYM2ZOG
    ProfitAndLoss: 4IKVLII2PI5WLFH6KRGJ2FZKOEKABWS7
    ProfitAndLossRowTemplate: IA6D7JRWSZGMVQ753BQKY6LQBW6KOECQ
  modules:
    Globals: 7MRF4YYUNNCRIFFCG2RNAVLNZZ6D3JKS
  server_modules:
    ServerModule1: AU6X5KHTXIMPUYI6U6AZ7UQH4YKZ4CYS
  assets:
    standard-page.html: 5N2FDSNY6M5PEG6DHKS5EZ4DLFMZAY5T
    theme.css: XR62POQAQ6RCPZQ77SXQU7HWG3Z5RX5C
